name: LateX CV to PDF

on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile test LaTeX document with Maths
        id: compile-latex-document-with-maths
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: output
          main_latex_file: main.tex
          ctan_packages: amsmath amsfonts lua-uni-algos
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab-maths
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/main.pdf

#       - name: Compile LaTeX document with TOC
#         id: compile-latex-document-with-toc
#         uses: ./
#         with:
#           output_dir: output
#           main_latex_file: resources/test-toc.tex
#           ctan_packages: lua-uni-algos
#           toc: true
#       - name: Upload PDF to the workflow tab
#         id: upload-workflow-tab-toc
#         uses: actions/upload-artifact@v2
#         with:
#           name: output-toc
#           path: output/test-toc.pdf
