name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          
      - name: push changes to remote
        run: |
          git config --global EytanSlotnik
          git config --global eythens@gmail.com


          git add &lt;pathspec&gt; git commit -m "commit message"
          git push
